=== Ashmit719/assignment-1--principles-of-databases--cs-365--fall-2026/xml/student.dtd
<!-- The students element contains one or more student elements. -->
<!ELEMENT students (student+)>

<!-- Each student contains the student's information in this order. -->
<!ELEMENT student (name, email, phone, academic-status, gpa, major, minor, enrollment-status, advisor, initial-enrollment-date, graduation-date)>

<!-- Each student must have an id attribute containing the student ID. -->
<!ATTLIST student id CDATA #REQUIRED>

<!-- The name element contains the parts of the student's name. -->
<!ELEMENT name (first-name, middle-name?, last-name, preferred-name?)>

<!-- The first-name element contains text. -->
<!ELEMENT first-name (#PCDATA)>

<!-- The middle-name element contains text when a middle name is provided. -->
<!ELEMENT middle-name (#PCDATA)>

<!-- The last-name element contains text. -->
<!ELEMENT last-name (#PCDATA)>

<!-- The preferred-name element contains text when a preferred name is provided. -->
<!ELEMENT preferred-name (#PCDATA)>

<!-- The email element contains the student's email address. -->
<!ELEMENT email (#PCDATA)>

<!-- The phone element contains the student's phone number. -->
<!ELEMENT phone (#PCDATA)>

<!-- The academic-status element contains the student's academic year. -->
<!ELEMENT academic-status (#PCDATA)>

<!-- The gpa element contains the student's grade point average. -->
<!ELEMENT gpa (#PCDATA)>

<!-- The major element contains the student's major. -->
<!ELEMENT major (#PCDATA)>

<!-- The minor element contains the student's minor. -->
<!ELEMENT minor (#PCDATA)>

<!-- The enrollment-status element contains the student's enrollment status. -->
<!ELEMENT enrollment-status (#PCDATA)>

<!-- The advisor element contains the student's advisor. -->
<!ELEMENT advisor (#PCDATA)>

<!-- The initial-enrollment-date element contains the student's initial enrollment date. -->
<!ELEMENT initial-enrollment-date (#PCDATA)>

<!-- The graduation-date element contains the student's graduation date. -->
<!ELEMENT graduation-date (#PCDATA)>

=== Ashmit719/assignment-1--principles-of-databases--cs-365--fall-2026/xml/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE students SYSTEM "student.dtd">

<students>
    <student id="1234567">
    <name>
      <first-name>Gordon</first-name>
      <middle-name>Matthew</middle-name>
      <last-name>Sumner</last-name>
      <preferred-name>Sting</preferred-name>
    </name>
    <email>sting@thepolice.com</email>
    <phone>212.123.4567</phone>
    <academic-status>first year</academic-status>
    <gpa>4.0</gpa>
    <major>Music</major>
    <minor>English</minor>
    <enrollment-status>full-time</enrollment-status>
    <advisor>Andy Summers</advisor>
    <initial-enrollment-date>08-25-1969</initial-enrollment-date>
    <graduation-date>05-01-1973</graduation-date>
  </student>
    <student id="4567890">
    <name>
      <first-name>Kim</first-name>
      <last-name>Thayil</last-name>
    </name>
    <email>kim@soundgarden.com</email>
    <phone>206.123.4567</phone>
    <academic-status>second year</academic-status>
    <gpa>3.0</gpa>
    <major>Philosophy</major>
    <minor>Music</minor>
    <enrollment-status>full-time</enrollment-status>
    <advisor>Chris Cornell</advisor>
    <initial-enrollment-date>08-25-1978</initial-enrollment-date>
    <graduation-date>05-01-1982</graduation-date>
  </student>

  <student id="8302438">
    <name>
      <first-name>Saul</first-name>
      <last-name>Hudson</last-name>
      <preferred-name>Slash</preferred-name>
    </name>
    <email>slash@gnr.com</email>
    <phone>213.456.8392</phone>
    <academic-status>fourth year</academic-status>
    <gpa>2.0</gpa>
    <major>Music</major>
    <minor>Criminal Justice</minor>
    <enrollment-status>part-time</enrollment-status>
    <advisor>Axl Rose</advisor>
    <initial-enrollment-date>08-25-1983</initial-enrollment-date>
    <graduation-date>05-01-1987</graduation-date>
  </student>

  <student id="2983928">
    <name>
      <first-name>Emily</first-name>
      <last-name>Kokal</last-name>
    </name>
    <email>emily@warpaint.com</email>
    <phone>213.123.7654</phone>
    <academic-status>third year</academic-status>
    <gpa>3.8</gpa>
    <major>Political Science</major>
    <minor>Law</minor>
    <enrollment-status>full-time</enrollment-status>
    <advisor>Jenny Lee Lindberg</advisor>
    <initial-enrollment-date>08-25-1998</initial-enrollment-date>
    <graduation-date>05-01-2002</graduation-date>
  </student>

  <student id="7645726">
    <name>
      <first-name>Mike</first-name>
      <last-name>Inez</last-name>
    </name>
    <email>mike@aic.com</email>
    <phone>213.444.3323</phone>
    <academic-status>second year</academic-status>
    <gpa>4.0</gpa>
    <major>Business Management</major>
    <minor>Math</minor>
    <enrollment-status>full-time</enrollment-status>
    <advisor>Jerry Cantrell</advisor>
    <initial-enrollment-date>08-25-1984</initial-enrollment-date>
    <graduation-date>05-01-1988</graduation-date>
  </student>
</students>
